import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Receipt } from '../types';
import { colors, spacing, typography } from '../theme';
import { Rule, ScreenHeader, StatusPill } from '../components/CounterUI';
import { areBothRefundsRecorded, formatReceiptParticipant, isRefundReceipt } from '../utils/receipt';
import { shareCounterEntity } from '../share';

export const FreshReceiptScreen: React.FC<{ receipt: Receipt; onBack: () => void; onViewDuel?: (duelId: string) => void }> = ({ receipt, onBack, onViewDuel }) => {
  const r: any = receipt;
  const a = formatReceiptParticipant({ display_name: r.captain_a_name, handle: r.captain_a_handle, wallet: r.captain_a_wallet });
  const b = formatReceiptParticipant({ display_name: r.captain_b_name, handle: r.captain_b_handle, wallet: r.captain_b_wallet });
  const cancelled = isRefundReceipt(r);
  const refundsRecorded = cancelled && areBothRefundsRecorded(r);
  const winnerWallet = !cancelled ? String(r.winner_wallet || '') : '';
  const winner = winnerWallet === r.captain_a_wallet ? a : winnerWallet === r.captain_b_wallet ? b : winnerWallet ? formatReceiptParticipant({ wallet: winnerWallet }) : '';
  const winnerPosition = Array.isArray(r.positions) ? r.positions.find((position: any) => position.user_wallet === winnerWallet) : null;
  const stakeA = Number(r.positions?.find((position: any) => position.user_wallet === r.captain_a_wallet)?.stake_amount ?? r.side_a_total ?? (Number(r.total_pool || 0) / 2));
  const stakeB = Number(r.positions?.find((position: any) => position.user_wallet === r.captain_b_wallet)?.stake_amount ?? r.side_b_total ?? (Number(r.total_pool || 0) / 2));
  const stakeCopy = stakeA === stakeB ? `${stakeA.toFixed(2)} cUSD each` : `${stakeA.toFixed(2)} / ${stakeB.toFixed(2)} cUSD`;
  const share = () => void shareCounterEntity({ type: 'RECEIPT', id: receipt.id, receipt });
  return <View style={styles.container}><ScreenHeader eyebrow="permanent proof" title="Receipt" onBack={onBack} right={<TouchableOpacity onPress={share} style={styles.share}><Text style={styles.shareText}>Share</Text></TouchableOpacity>} /><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Text style={styles.receiptMark}>COUNTER</Text><Text style={styles.heroTitle}>{cancelled ? 'No agreement' : 'Duel settled'}</Text><Text style={styles.heroBody}>{cancelled ? (refundsRecorded ? 'No agreement. Both stakes were returned.' : 'No agreement. Both stakes are being returned.') : 'The result is recorded between two people.'}</Text></View><View style={styles.matchup}><Text style={styles.person}>{a}</Text><Text style={styles.vs}>vs</Text><Text style={styles.person}>{b}</Text></View><Rule /><Text style={styles.section}>THE TAKE</Text><Text style={styles.proposition}>{r.topic || r.proposition_a || 'Counter Duel'}</Text>{r.take_content ? <Text style={styles.reason}>{r.take_content}</Text> : null}<View style={styles.terms}><Text style={styles.termLabel}>Stake</Text><Text style={styles.termValue}>{stakeCopy}</Text><Text style={styles.termLabel}>Outcome</Text><Text style={styles.termValue}>{cancelled ? 'No agreement' : r.resolution_summary || 'Settled'}</Text>{!cancelled && winner ? <><Text style={styles.termLabel}>Winner</Text><Text style={styles.termValue}>{winner}</Text></> : null}<Text style={styles.termLabel}>Total outcome</Text><Text style={styles.termValue}>{Number(r.total_pool || 0).toFixed(2)} cUSD</Text><Text style={styles.termLabel}>Settlement</Text><StatusPill label={cancelled ? (refundsRecorded ? 'Refunded / recorded' : 'Refund pending') : (winnerPosition?.claimed ? 'Claimed / recorded' : 'Result recorded')} tone={cancelled ? 'warning' : 'success'} /></View><Text style={styles.section}>TECHNICAL PROOF</Text><View style={styles.proof}><Text style={styles.proofLabel}>Transaction</Text><Text style={styles.proofValue}>{r.onchain_signature ? `${String(r.onchain_signature).slice(0, 10)}…${String(r.onchain_signature).slice(-8)}` : 'Recorded by Counter'}</Text><Text style={styles.proofLabel}>Receipt ID</Text><Text style={styles.proofValue}>{r.id}</Text></View>{onViewDuel ? <TouchableOpacity style={styles.viewDuel} onPress={() => onViewDuel(receipt.duel_id)}><Text style={styles.viewDuelText}>View Duel journey ›</Text></TouchableOpacity> : null}</ScrollView></View>;
};
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, content: { paddingHorizontal: spacing.lg, paddingBottom: 112 }, share: { minHeight: 48, justifyContent: 'center' }, shareText: { ...typography.captionBold, color: colors.brandPrimary }, hero: { paddingVertical: spacing.xl }, receiptMark: { ...typography.captionBold, color: colors.brandPrimary, letterSpacing: 2 }, heroTitle: { ...typography.display, marginTop: spacing.md }, heroBody: { ...typography.bodyMuted, marginTop: spacing.sm }, matchup: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.lg }, person: { ...typography.bodyBold, flex: 1 }, vs: { ...typography.caption, color: colors.textMuted }, section: { ...typography.captionBold, color: colors.textMuted, marginTop: spacing.xl, marginBottom: spacing.sm }, proposition: { ...typography.h2, lineHeight: 28 }, reason: { ...typography.bodyMuted, marginTop: spacing.sm }, terms: { marginTop: spacing.xl, paddingVertical: spacing.lg, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.divider, gap: spacing.xs }, termLabel: { ...typography.caption, color: colors.textMuted, marginTop: spacing.sm }, termValue: { ...typography.bodyBold }, proof: { backgroundColor: colors.surfaceLight, borderRadius: 16, padding: spacing.lg, gap: spacing.xs }, proofLabel: { ...typography.caption, color: colors.textMuted, marginTop: spacing.sm }, proofValue: { ...typography.mono }, viewDuel: { minHeight: 54, justifyContent: 'center', alignItems: 'center' }, viewDuelText: { ...typography.bodyBold, color: colors.brandPrimary },
});
