import React from 'react';
import { ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Receipt } from '../types';
import { colors, spacing, typography } from '../theme';
import { Rule, ScreenHeader, StatusPill } from '../components/CounterUI';
import { formatUserDisplayName } from '../utils/identity';

export const FreshReceiptScreen: React.FC<{ receipt: Receipt; onBack: () => void; onViewDuel?: (duelId: string) => void }> = ({ receipt, onBack, onViewDuel }) => {
  const r: any = receipt; const a = formatUserDisplayName({ display_name: r.captain_a_name, handle: r.captain_a_handle, wallet: r.captain_a_wallet }); const b = formatUserDisplayName({ display_name: r.captain_b_name, handle: r.captain_b_handle, wallet: r.captain_b_wallet }); const cancelled = /refund|agreement/i.test(String(r.resolution_summary || '')) && !r.winner_wallet;
  const share = () => Share.share({ message: `Counter Receipt · ${a} vs ${b} · ${r.resolution_summary || 'Duel settled'}` });
  return <View style={styles.container}><ScreenHeader eyebrow="permanent proof" title="Receipt" onBack={onBack} right={<TouchableOpacity onPress={share} style={styles.share}><Text style={styles.shareText}>Share</Text></TouchableOpacity>} /><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Text style={styles.receiptMark}>COUNTER</Text><Text style={styles.heroTitle}>{cancelled ? 'No agreement' : 'Duel settled'}</Text><Text style={styles.heroBody}>{cancelled ? 'Both stakes were returned.' : 'The result is recorded between two people.'}</Text></View><View style={styles.matchup}><Text style={styles.person}>{a}</Text><Text style={styles.vs}>vs</Text><Text style={styles.person}>{b}</Text></View><Rule /><Text style={styles.section}>THE TAKE</Text><Text style={styles.proposition}>{r.topic || r.proposition_a || 'Counter Duel'}</Text>{r.take_content ? <Text style={styles.reason}>{r.take_content}</Text> : null}<View style={styles.terms}><Text style={styles.termLabel}>Stake each</Text><Text style={styles.termValue}>{Number(r.total_pool || 0) / 2} cUSD</Text><Text style={styles.termLabel}>Outcome</Text><Text style={styles.termValue}>{r.resolution_summary || 'Settled'}</Text><Text style={styles.termLabel}>Settlement</Text><StatusPill label={cancelled ? 'Refunded' : 'Claimed / recorded'} tone={cancelled ? 'warning' : 'success'} /></View><Text style={styles.section}>TECHNICAL PROOF</Text><View style={styles.proof}><Text style={styles.proofLabel}>Transaction</Text><Text style={styles.proofValue}>{r.onchain_signature ? `${String(r.onchain_signature).slice(0, 10)}…${String(r.onchain_signature).slice(-8)}` : 'Recorded by Counter'}</Text><Text style={styles.proofLabel}>Receipt ID</Text><Text style={styles.proofValue}>{r.id}</Text></View>{onViewDuel ? <TouchableOpacity style={styles.viewDuel} onPress={() => onViewDuel(receipt.duel_id)}><Text style={styles.viewDuelText}>View Duel journey ›</Text></TouchableOpacity> : null}</ScrollView></View>;
};
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, content: { paddingHorizontal: spacing.lg, paddingBottom: 80 }, share: { minHeight: 48, justifyContent: 'center' }, shareText: { ...typography.captionBold, color: colors.brandPrimary }, hero: { paddingVertical: spacing.xl }, receiptMark: { ...typography.captionBold, color: colors.brandPrimary, letterSpacing: 2 }, heroTitle: { ...typography.display, marginTop: spacing.md }, heroBody: { ...typography.bodyMuted, marginTop: spacing.sm }, matchup: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.lg }, person: { ...typography.bodyBold, flex: 1 }, vs: { ...typography.caption, color: colors.textMuted }, section: { ...typography.captionBold, color: colors.textMuted, marginTop: spacing.xl, marginBottom: spacing.sm }, proposition: { ...typography.h2, lineHeight: 28 }, reason: { ...typography.bodyMuted, marginTop: spacing.sm }, terms: { marginTop: spacing.xl, paddingVertical: spacing.lg, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.divider, gap: spacing.xs }, termLabel: { ...typography.caption, color: colors.textMuted, marginTop: spacing.sm }, termValue: { ...typography.bodyBold }, proof: { backgroundColor: colors.surfaceLight, borderRadius: 16, padding: spacing.lg, gap: spacing.xs }, proofLabel: { ...typography.caption, color: colors.textMuted, marginTop: spacing.sm }, proofValue: { ...typography.mono }, viewDuel: { minHeight: 54, justifyContent: 'center', alignItems: 'center' }, viewDuelText: { ...typography.bodyBold, color: colors.brandPrimary },
});
