import React, { useCallback, useEffect, useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { ActivityNotification, Challenge } from '../types';
import { api, isUnreachable } from '../api';
import { colors, spacing, typography } from '../theme';
import { EmptyState, Rule, ScreenHeader, StatusPill } from '../components/CounterUI';
import { formatRelativeTime } from '../utils/identity';

export const FreshActivityScreen: React.FC<{ onSelectNotification: (item: ActivityNotification) => void; onOpenChallenge: (challenge: Challenge) => void; focusSignal?: number; onActionableCountChange?: (count: number) => void }> = ({ onSelectNotification, onOpenChallenge, focusSignal, onActionableCountChange }) => {
  const [items, setItems] = useState<ActivityNotification[]>([]); const [challenges, setChallenges] = useState<Challenge[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); const [next, pending] = await Promise.all([api.getActivity(), api.getChallenges()]); setItems(Array.isArray(next) ? next : []); setChallenges(Array.isArray(pending) ? pending : []); } catch (err: any) { setError(isUnreachable(err) ? 'NETWORK_UNREACHABLE' : 'Activity could not load.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { load(); }, [load]); const focusRef = React.useRef(focusSignal); useEffect(() => { if (focusSignal !== undefined && focusSignal !== focusRef.current) { focusRef.current = focusSignal; setRefreshing(true); load(); } }, [focusSignal, load]);
  const actionable = items.filter((x) => !x.is_read && ['CHALLENGE_RECEIVED', 'READY_TO_SETTLE', 'OPPONENT_SUBMITTED_RESULT', 'REFUND_READY', 'WINNINGS_READY'].includes(x.type)).length + challenges.filter((x) => x.status === 'PROPOSED' || x.status === 'COUNTERED').length; useEffect(() => onActionableCountChange?.(actionable), [actionable, onActionableCountChange]);
  const today = new Date().toDateString(); const groups = [{ title: 'Today', rows: items.filter((x) => new Date(x.created_at).toDateString() === today) }, { title: 'Earlier', rows: items.filter((x) => new Date(x.created_at).toDateString() !== today) }].filter((g) => g.rows.length);
  const handle = (item: ActivityNotification) => { const challenge = challenges.find((c) => c.id === item.target_id); if (challenge) onOpenChallenge(challenge); else onSelectNotification(item); };
  const humanTitle = (item: ActivityNotification) => item.title?.replace('You were Challenged to a Duel!', 'New challenge') || item.type.replaceAll('_', ' ');
  return <View style={styles.container}><ScreenHeader eyebrow="what needs your attention" title="Activity" right={actionable ? <StatusPill label={`${actionable} new`} tone="accent" /> : undefined} />{loading ? <View style={styles.loading}><Text style={styles.loadingText}>Catching up…</Text></View> : error ? <EmptyState title={error} body="Check your connection and try again." action="Retry" onAction={load} /> : <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} tintColor={colors.brandPrimary} />} contentContainerStyle={items.length ? styles.content : styles.emptyContent}>{groups.length ? groups.map((group) => <View key={group.title}><Text style={styles.group}>{group.title}</Text>{group.rows.map((item) => <View key={item.id}><TouchableOpacity style={styles.item} onPress={() => handle(item)} activeOpacity={0.84}><View style={[styles.unread, !item.is_read && styles.unreadOn]} /><View style={styles.itemCopy}><View style={styles.itemTop}><Text style={styles.itemTitle}>{humanTitle(item)}</Text><Text style={styles.time}>{formatRelativeTime(item.created_at)}</Text></View><Text style={styles.message}>{item.message}</Text><Text style={styles.actionHint}>{['CHALLENGE_RECEIVED', 'OPPONENT_SUBMITTED_RESULT', 'READY_TO_SETTLE', 'REFUND_READY'].includes(item.type) ? 'Open in Duels' : 'View details'} <Text style={styles.arrow}>›</Text></Text></View></TouchableOpacity><Rule /></View>)}</View>) : <EmptyState title="You’re all caught up" body="Challenges, Duel updates, and settlement actions will appear here." />}</ScrollView>}</View>;
};
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, content: { paddingBottom: 80 }, emptyContent: { flexGrow: 1 }, group: { ...typography.captionBold, color: colors.textMuted, textTransform: 'uppercase', paddingHorizontal: spacing.lg, paddingTop: spacing.lg, paddingBottom: spacing.sm }, item: { flexDirection: 'row', paddingHorizontal: spacing.lg, paddingVertical: spacing.lg }, unread: { width: 7, height: 7, borderRadius: 4, backgroundColor: 'transparent', marginTop: 7, marginRight: spacing.md }, unreadOn: { backgroundColor: colors.brandPrimary }, itemCopy: { flex: 1 }, itemTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: spacing.sm }, itemTitle: { ...typography.bodyBold, flex: 1 }, time: { ...typography.caption }, message: { ...typography.bodyMuted, marginTop: 5 }, actionHint: { color: colors.brandPrimary, ...typography.captionBold, marginTop: spacing.md }, arrow: { fontSize: 18 }, rule: { marginLeft: spacing.lg }, loading: { padding: spacing.xl, alignItems: 'center' }, loadingText: { ...typography.bodyMuted },
});
