import React, { useCallback, useEffect, useState } from 'react';
import { FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Challenge, Duel, Portfolio } from '../types';
import { colors, spacing, typography, touchMin } from '../theme';
import { api, isUnreachable } from '../api';
import { EmptyState, Rule, ScreenHeader, StatusPill } from '../components/CounterUI';
import { formatRelativeTime, formatUserDisplayName } from '../utils/identity';
import { mapDuelState, stateLabel } from '../utils/duelState';
import { loadDuelsScreenData } from '../utils/duelsLoad';
import { useSyncRefresh } from '../syncCoordinator';

type Filter = 'INCOMING' | 'SENT' | 'ACTIVE' | 'CLAIMABLE' | 'COMPLETED';
const FILTERS: { key: Filter; label: string }[] = [{ key: 'INCOMING', label: 'Incoming' }, { key: 'SENT', label: 'Sent' }, { key: 'ACTIVE', label: 'Active' }, { key: 'CLAIMABLE', label: 'Claimable' }, { key: 'COMPLETED', label: 'Completed' }];
export const FreshDuelsScreen: React.FC<{ userWallet: string | null; onSelectDuel: (duel: Duel) => void; onOpenChallenge: (challenge: Challenge) => void; createdChallenge?: Challenge | null; focusSignal?: number; onActionableCountChange?: (count: number) => void }> = ({ userWallet, onSelectDuel, onOpenChallenge, createdChallenge, focusSignal, onActionableCountChange }) => {
  const [duels, setDuels] = useState<Duel[]>([]); const [challenges, setChallenges] = useState<Challenge[]>([]); const [portfolio, setPortfolio] = useState<Portfolio | null>(null); const [filter, setFilter] = useState<Filter>('INCOMING'); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); const result = await loadDuelsScreenData(() => api.getDuels({ isArena: false }), () => api.getChallenges(), () => api.getPortfolio(), !!userWallet); setDuels(result.duels); setChallenges(result.challenges); setPortfolio(result.portfolio); if (result.portfolioUnavailable) console.warn('[DUELS] portfolio unavailable; base Duel list remains usable'); } catch (err: any) { setError(isUnreachable(err) ? 'NETWORK_UNREACHABLE' : 'Duels could not load.'); } finally { setLoading(false); setRefreshing(false); } }, [userWallet]);
  const syncLoad = useSyncRefresh(load);
  useEffect(() => { void syncLoad(); }, [syncLoad]); const focusRef = React.useRef(focusSignal); useEffect(() => { if (focusSignal !== undefined && focusSignal !== focusRef.current) { focusRef.current = focusSignal; setRefreshing(true); void syncLoad(); } }, [focusSignal, syncLoad]);
  const visibleChallenges = createdChallenge && ['PROPOSED', 'COUNTERED'].includes(createdChallenge.status) && !challenges.some((c) => c.id === createdChallenge.id) ? [createdChallenge, ...challenges] : challenges;
  const incoming = visibleChallenges.filter((c) => c.creator_wallet === userWallet); const sent = visibleChallenges.filter((c) => c.challenger_wallet === userWallet); const claimable = new Set((portfolio?.positions || []).filter((p) => p.claim_state === 'CLAIMABLE').map((p) => p.duel_id)); const completed = new Set((portfolio?.positions || []).filter((p) => p.claim_state !== 'OPEN').map((p) => p.duel_id));
  const state = (d: Duel) => mapDuelState({ duel: d, userWallet, mutualState: d.mutualState, myVoteSubmitted: d.myVoteSubmitted, otherVoteSubmitted: d.otherVoteSubmitted });
  const actionable = incoming.length + duels.filter((d) => state(d) === 'READY_TO_SETTLE' || claimable.has(d.id)).length; useEffect(() => onActionableCountChange?.(actionable), [actionable, onActionableCountChange]);
  const visible = filter === 'INCOMING' ? incoming : filter === 'SENT' ? sent : duels.filter((d) => filter === 'ACTIVE' ? !['CANCELLED'].includes(d.status) && !d.status.startsWith('RESOLVED') : filter === 'CLAIMABLE' ? claimable.has(d.id) : (d.status.startsWith('RESOLVED') || d.status === 'CANCELLED') && (completed.has(d.id) || d.captain_a_wallet === userWallet || d.captain_b_wallet === userWallet));
  const renderChallenge = ({ item }: { item: Challenge }) => { const isIncoming = item.creator_wallet === userWallet; const other = isIncoming ? formatUserDisplayName({ display_name: item.challenger_name, handle: item.challenger_handle, wallet: item.challenger_wallet }) : formatUserDisplayName({ display_name: item.creator_name, handle: item.creator_handle, wallet: item.creator_wallet }); return <View><TouchableOpacity style={styles.row} onPress={() => isIncoming && onOpenChallenge(item)} activeOpacity={isIncoming ? 0.8 : 1}><View style={styles.rowTop}><StatusPill label={isIncoming ? 'Incoming' : 'Sent'} tone={isIncoming ? 'accent' : 'muted'} /><Text style={styles.time}>{formatRelativeTime(item.created_at)}</Text></View><Text style={styles.rowTitle}>{isIncoming ? `${other} challenged your Take` : `You challenged ${other}`}</Text><Text style={styles.rowDetail}>{item.proposition_b}</Text><Text style={styles.rowStatus}>{isIncoming ? 'Review terms' : 'Waiting for response'}</Text></TouchableOpacity><Rule /></View>; };
  const renderDuel = ({ item }: { item: Duel }) => { const meA = item.captain_a_wallet === userWallet; const other = formatUserDisplayName({ display_name: meA ? item.captain_b_name : item.captain_a_name, handle: meA ? item.captain_b_handle : item.captain_a_handle, wallet: meA ? item.captain_b_wallet : item.captain_a_wallet }); const label = state(item); const tone = label === 'READY_TO_SETTLE' || label === 'MISMATCH' || label === 'TIMEOUT' ? 'warning' : label === 'MATCHED_RESULT' ? 'success' : 'muted'; return <View><TouchableOpacity style={styles.row} onPress={() => onSelectDuel(item)} activeOpacity={0.84}><View style={styles.rowTop}><StatusPill label={stateLabel(label)} tone={tone as any} /><Text style={styles.time}>{formatRelativeTime(item.created_at)}</Text></View><Text style={styles.rowTitle}>{item.proposition_a}</Text><Text style={styles.rowDetail}>vs {item.proposition_b}</Text><View style={styles.rowBottom}><Text style={styles.rowStatus}>{other} · {Number(item.side_a_total || 0) + Number(item.side_b_total || 0)} cUSD in play</Text><Text style={styles.chevron}>›</Text></View></TouchableOpacity><Rule /></View>; };
  return <View style={styles.container}><ScreenHeader title="Duels" right={<StatusPill label={`${actionable} to do`} tone={actionable ? 'accent' : 'muted'} />} /><FlatList horizontal data={FILTERS} keyExtractor={(x) => x.key} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters} renderItem={({ item }) => <TouchableOpacity style={[styles.filter, filter === item.key && styles.filterActive]} onPress={() => setFilter(item.key)} accessibilityRole="tab" accessibilityState={{ selected: filter === item.key }}><Text numberOfLines={1} style={[styles.filterText, filter === item.key && styles.filterTextActive]}>{item.label}</Text></TouchableOpacity>} />{loading ? <View style={styles.loading}><Text style={styles.loadingText}>Loading your Duels…</Text></View> : error ? <EmptyState title={error} body="Check your connection and try again." action="Retry" onAction={syncLoad} /> : <FlatList data={visible} keyExtractor={(x: any) => x.id} renderItem={filter === 'INCOMING' || filter === 'SENT' ? renderChallenge as any : renderDuel as any} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void syncLoad(); }} tintColor={colors.brandPrimary} />} contentContainerStyle={visible.length ? styles.list : styles.emptyList} ListEmptyComponent={<EmptyState title={filter === 'INCOMING' ? 'No incoming challenges' : filter === 'SENT' ? 'No sent challenges' : 'Nothing here yet'} body={filter === 'INCOMING' ? 'When someone challenges your Take, it will show up here.' : 'Your next move will appear here when there is one.'} />} />}</View>;
};
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, filters: { paddingHorizontal: spacing.lg, paddingBottom: spacing.md, gap: spacing.xs }, filter: { height: 38, minHeight: 38, flexShrink: 0, alignItems: 'center', paddingHorizontal: spacing.md, justifyContent: 'center', borderRadius: 20 }, filterActive: { backgroundColor: colors.surfaceHighlight }, filterText: { ...typography.captionBold, color: colors.textMuted }, filterTextActive: { color: colors.warmIvory }, list: { paddingBottom: 112 }, emptyList: { flexGrow: 1, paddingBottom: 112 }, row: { paddingHorizontal: spacing.lg, paddingVertical: spacing.lg }, rowTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.md }, time: { ...typography.caption }, rowTitle: { ...typography.h2, fontSize: 19, lineHeight: 25 }, rowDetail: { ...typography.bodyMuted, marginTop: 5 }, rowStatus: { ...typography.captionBold, color: colors.textSecondary, marginTop: spacing.md }, rowBottom: { flexDirection: 'row', alignItems: 'center', marginTop: spacing.sm }, chevron: { marginLeft: 'auto', color: colors.brandPrimary, fontSize: 26 }, loading: { padding: spacing.xl, alignItems: 'center' }, loadingText: { ...typography.bodyMuted },
});
